spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx/xxx?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 2000
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: select 'x'
    filters: stat

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/*/*.xml

pagehelper:
  helper-dialect: mysql